spring.application.name=oficina-mecanica
spring.profiles.default=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html

server.error.include-stacktrace=never
server.error.include-message=never
