spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.docker.compose.enabled=false
spring.flyway.locations=classpath:db/migration

server.forward-headers-strategy=${FORWARD_HEADERS_STRATEGY:none}
